const data = {
    animals: [
        {
            _id: '1',
            name: 'John',
            category: 'Dog',
            image: '/images/a1.jpg',
            status: 'Atiduodamas',
            date: '2020-11-11',
            description: 'Nice dog',
        },
        {
            _id: '2',
            name: 'Petras',
            category: 'Cat',
            image: '/images/a2.jpg',
            status: 'Atiduodamas',
            date: '2020-11-11',
            description: 'Nice cat',
        },
        {
            _id: '3',
            name: 'Mr Dog',
            category: 'Dog',
            image: '/images/a3.jpg',
            status: 'Ieskomas',
            date: '2020-11-10',
            description: 'Nice dog',
        },
        {
            _id: '4',
            name: 'Jonas',
            category: 'Cat',
            image: '/images/a4.jpg',
            status: 'Atiduodamas',
            date: '2020-10-11',
            description: 'Nice cat',
        },
        {
            _id: '5',
            name: 'John',
            category: 'Dog',
            image: '/images/a5.jpg',
            status: 'Atiduodamas',
            date: '2020-11-11',
            description: 'Nice dog',
        },
        {
            _id: '6',
            name: 'John',
            category: 'Dog',
            image: '/images/a6.jpg',
            status: 'Atiduodamas',
            date: '2020-11-11',
            description: 'Nice dog',
        },
        {
            _id: '7',
            name: 'John',
            category: 'Dog',
            image: '/images/a7.jpg',
            status: 'Atiduodamas',
            date: '2020-11-11',
            description: 'Nice dog',
        },
    ], 
};
export default data;